### ISSUE TITLE
Offer to choose text area instead of text field

### ISSUE THREAD

**Issue by Th3R3alPr0** [pixelant/pxa_survey#13]
Hello,
I have some questions in my survey where the user has to justify his answer he made earlier. So he needs to type a little text. So while he's writing his answer and hits enter to make a line break, the survey gets send. If I edit the template and make a text area out of the text fields all the text fields change. Is it possible to choose from one or another when creating an answer?

**Comment by anjeylink** [comment]
Hi, are you asking for textarea instead of text input, for user "free answer"?

**Comment by anjeylink** [comment]
fixed in #16 You can now choose what type field for "free answer" to show, it can be simple input or textarea.
