### ISSUE TITLE
Migrate to TYPO3 9.x and PHP 7.2

### ISSUE THREAD

**Issue by nicozerr** [pixelant/pxa_survey#15]
Hi.

TYPO3 9.x has been released. Will ext:pxa_survey be migrated for this version ?

Thank you.

**Comment by anjeylink** [comment]
Hi, yes, definitely.

**Comment by extcode** [comment]
Hi, I test the extension with a very small survey. UserAnswers will be saved to the database with question=0. The UserAnswer object seems to be correct before adding to the repository. The question attribute holds the correct data.

**Comment by anjeylink** [comment]
@extcode Hi, I have created a ticket on forge, but no answer yet. 
This is only one thing that prevent it from release for TYPO3 v9

https://forge.typo3.org/issues/86252

**Comment by extcode** [comment]
I've added a patch to TYPO3 core. This will fix the problem. The parameter to _isDirty() was removed less than three weeks ago. The issue which remove the parameter only mentions code cleanup, but nothing more.

**Comment by extcode** [comment]
Patch was applied. Saving UserAnswers with current master should save the relation to the question.

**Comment by anjeylink** [comment]
fixed in #16
