### ISSUE TITLE
Free text input "0" not correctly validated and saved

### ISSUE THREAD

**Issue by theorak** [pixelant/pxa_survey#17]
The user answer for a free text field is not correctly validated and not saved when a factual "0" is entered.

Example:
Question, how many of X are in your supplies?
Answer, required, but can be "0" or any other number.

For now answers like this are registered as "not given" by the validation and the entires would not be saved for unrequired fields.

Also, would you offer validation Options for numbers only?

**Comment by anjeylink** [comment]
@theorak Hi, thx for feedback. 
Regarding numbers validation, it'll require implementing new validation type. I'll create a new issue/feature request for this
