### ISSUE TITLE
TYPO3 10 LTS compatibility

### ISSUE THREAD

**Issue by tobikummer** [pixelant/pxa_survey#30]
Is it planed to add a TYPO3 10 LTS compatibility?
If yes, when?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
*bump* :) We need to know this, too.

**Comment by dmh** [comment]
Hi guys @tobikummer @h-e-l-l-o-w-o-r-l-d 
For now, we are not often using this extension for our projects, so it is a low priority for us. And considering this we are not able to tell you any plans or time estimations for 10 LTS compatibility. But at the same time, we are open to any pull-requests from your side. Thanks in advance.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Done: https://github.com/pixelant/pxa_survey/pull/33

**Comment by extcode** [comment]
@dmh What is the status here? Did you find time to look at #33 in the meantime? Is it a possible option to remove the support for TYPO3 v8 or is that the problem why there is no feedback yet. We would like to use this in a project.

**Comment by klodeckl** [comment]
@h-e-l-l-o-w-o-r-l-d seems to work fine. Thank you!

**Comment by MattiasNilsson** [comment]
A TYPO3 v10 version is now published: https://github.com/pixelant/pxa_survey/releases/tag/v2.0.0
